# Generated by Django 6.0.4 on 2026-05-19 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_pro', models.CharField(max_length=20)),
                ('adresse_cabinet', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('annees_experience', models.PositiveIntegerField(default=0)),
                ('numero_ordre', models.CharField(blank=True, max_length=50)),
                ('est_actif', models.BooleanField(default=True)),
                ('tarif_consultation', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_medecin', to=settings.AUTH_USER_MODEL)),
                ('specialites', models.ManyToManyField(related_name='medecins', to='doctors.specialite')),
            ],
            options={
                'verbose_name': 'Médecin',
                'ordering': ['utilisateur__last_name'],
            },
        ),
    ]
