# Generated by Django 6.0.4 on 2026-05-19 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indisponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilites', to='doctors.medecin')),
            ],
            options={
                'verbose_name': 'Indisponibilité',
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('duree_rdv', models.IntegerField(default=30, help_text='Durée en minutes')),
                ('est_active', models.BooleanField(default=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='doctors.medecin')),
            ],
            options={
                'verbose_name': 'Disponibilité',
                'ordering': ['jour', 'heure_debut'],
                'unique_together': {('medecin', 'jour', 'heure_debut')},
            },
        ),
    ]
